name: Run Lark Bot

on:
  schedule:
    # 05:00, 07:00, 10:00 UTC = 09:00, 11:00, 14:00 giờ Georgia (MỖI NGÀY)
    - cron: '0 5,7,10 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python lark_bot.py
