name: Run Lark Bot

on:
  schedule:
    # Chạy 09:05, 11:05, 14:05 theo giờ Georgia mỗi ngày
    - cron: '5 9,11,14 * * *'
      timezone: 'Asia/Tbilisi'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python lark_bot.py
